feat(app): Restrict user infos for different organisation types
gip-inclusion/rdv-insertion pull request #2239
Opened 2024-07-25 21:00 UTC by aminedhobb

closes #2116 

## Contexte

Nous commençons à avoir une typologie d'organisations très différentes qui utilise rdv-insertion, allant des `SIAE` aux conseils départementaux. Certains attributs qui font sens dans un cas ne font pas forcément dans l'autre, comme l'ID interne au département. Certains attributs comme le NIR ne doivent quant à eux par être stockable dans certains contextes pour des raisons RGPD.

## Implémentation 

### Logiques d'autorisations

J'ai pensé que  la classe `UserPolicy` était le meilleur endroit pour implémenter cette logique d'autorisations en fonction des types d'organisation.
À partir d'un usager et de l'agent connecté, on va regarder les organisations que ces deux entités  ont en commun pour décider quels attributs sont autorisés à être manipulés. 
Souvent, on doit en plus passer l'organisation sur laquelle on va assigner l'agent pour déterminer quels attributs sont autorisés.

### Au moment de sauvegarder un usager 

J'introduis une nouvelle méthode  `user#assign_authorized_attributes` qui va filtrer les attributs qu'on veut assigner à l'usager en ne gardant que les atttributs autorisés. Cette méthode est utilisé aux différents endroit où on peut assigner de nouveaux attributs à  un usager.

### Dans les vues de l'application

J'utilise des nouvelles méthodes de helper (qui font appel à la policy) pour pouvoir voir quels attributs on peut afficher ou non dans les différentes pages de l'application. 

### Au niveau de l'API

Pour l'API je filtre les attributs que l'on renvoie directement dans le `UserBlueprint`.
Cela donne l'avantage d'être très confiant sur le fait que l'on ne va pas renvoyer par erreur des attributs non autorisés.

Après je pense que le blueprint ne devrait probablement pas être responsable de ce filtre. Malheureusement, il y a énormément d'endroit où les données sont sérialisées pour être envoyées dans l'appli front, et les répertorier puis appliquer ces filtres partout aurait été trop fastidieux ici. Par contre je suis pour qu'on reprenne ça une fois que l'on aura supprimé l'appli react (et que donc on aura substantiellement réduit les endroits où ces données vont être sérialisés). 

Aussi, pour rester dans ce sujet, je pense que l'override de la méthode `as_json` dans le module `Serializable` est pratique dans le sens où là encore on est sûr de toujours sérialiser nos modèles via les blueprint et donc via nos règles, mais là aussi c'est beaucoup contraignant: on ne peut pas appeler `user.as_json` si un `Current.agent` n'est pas défini. Je serais pour l'enlever dès qu'on aura réduit les endroits où on sérialise nos models.

### Au niveau des webhooks 

Dans la partie précédente j'explique que l'on filtre les champs renvoyés par `UserBlueprint` en fonction des autorisations des agents connectés. Mais lorsqu'on envoie un webhook il n'y a pas d'agent connecté.
Cependant, on a mis en place un changement dans #2230 et #2231 qui nous permet de lier chaque envoi de webhooks à une organisation précise. Ainsi, on peut passer en option le type d'organisation pour lequel on envoie les webhooks pour pouvoir filtrer les données que l'on veut envoyer

## Changement annexes

Je me suis rendu compte en implémentant cette feature qu'il n'y avait pas de raisons pour que notre endpoint de search (`users/searches#create`) renvoie des usagers d'organisations auquel l'agent n'appartient pas. Je change donc ce comportement pour ne renvoyer que les usagers auquel on a déjà accès.

2024-07-29 09:36 UTC, Michaelvilleneuve commented on app/helpers/users_helper.rb
> +    UserPolicy.assignable_user_attribute?(user:, attribute_name:, organisation_to_be_assigned:)
Je pense qu'ici c'est pas `organisation_to_be_assigned`, mais plutôt `assigning_organisation`, ie: l'organisation qui assigne, plutôt que organisation à assigner

2024-07-29 09:38 UTC, Michaelvilleneuve commented on app/models/concerns/webhook_deliverable.rb
> +      generate_webhook_payload(:destroyed, endpoint.organisation_type)
pas évident de saisir pourquoi on a besoin de passer `organisation_type` dans ce fichier

2024-07-29 09:40 UTC, Michaelvilleneuve commented on app/models/file_configuration.rb
> +  end
Peut-être plus simple comme ça : 
```ruby
  User.attribute_names.find { |n| n == attribute_name.delete_suffix("_column") }
```

2024-07-29 09:43 UTC, Michaelvilleneuve commented on app/policies/user_policy.rb
> +  }
pourquoi ne pas faire de `User.symbolized_attribute_names` le défaut et appeler plutôt 
```ruby
  RESTRICTED_ATTRIBUTES = {
     delegataire_rsa: [:nir],
     siae: [:nir, :department_internal_id],
     autre: [:nir, :department_internal_id],
   }  
```

2024-07-29 09:44 UTC, Michaelvilleneuve commented on app/policies/user_policy.rb
> +  def self.authorized_user_attributes_for(user:, agent: Current.agent, organisation_to_be_assigned: nil)
idem du coup ici je pense que `organisation_to_be_assigned ` est incorrect et devrait être `assigner` ou `organisation_assigning`

2024-07-29 09:45 UTC, Michaelvilleneuve requested changes
Très très cool, super utile comme PR, merci, juste quelques petits changements qui me semble nécessaire, je te laisse voir ça 🙏

2024-07-29 18:20 UTC, aminedhobb commented
Merci pour ta review et tes suggestions @Michaelvilleneuve 🙏 !!
J'ai appliqué toutes tes suggestions ici: https://github.com/gip-inclusion/rdv-insertion/pull/2239/commits/ae6417ab0c8810774db992248381394b50e5a55d

2024-07-30 07:42 UTC, Michaelvilleneuve approved these changes
Merci pour les changements !

2024-07-30 07:51 UTC, merged