refactor(invitations): invitation expiration logic
gip-inclusion/rdv-insertion pull request #2319
Opened 2024-09-10 22:42 UTC by aminedhobb

Avant d'attaquer #2297 où l'on veut exposer dans l'API la date d'expiration de l'invitation, j'ai voulu renommer la colonne `valid_until` de la table `invitations` en `expires_at`. Se faisant, j'ai relu le code lié à la validité de l'invitation et je me suis rendu compte que beaucoup de choses pouvaient être changées et simplifiée dans cette partie du code qui date des débuts de l'application. 
J'énumère ces changements ci-dessous.

## Renommage des colonnes

* Comme énoncé en introduction, je renomme la colonne `valid_until` en `expires_at` qui est plus parlante. J'en profite pour ajouter un index sur cette colonne car comme on le verra dans la partie suivante on va souvent requêter par rapport à cette colonne pour récupérer les invitations valides ou invalides dans l'application.
* Je renomme également la colonne `number_of_days_before_action_required` en `invitation_duration_in_days` qui est beaucoup plus parlant sur ce à quoi sert exactement cette colonne

Ce renommage a été fait ici https://github.com/gip-inclusion/rdv-insertion/commit/1b030db4249992b84a86e169346711080aac6ad3

## Ne plus utiliser la `category_configuration` pour récupérer les invitations dont le délai a été dépassé

### Lorsque l'on requête les suivis où une intervention est nécessaire 

Lorsqu'on coche le filtre "Usagers avec intervention nécessaire", on récupère entre autres les suivis (`follow_ups`) dont les invitations n'ont pas entrainé de prise de rdv (on affiche alors le statut "**Invitation en attente de réponse (Délai dépassé)**"). Cette requête est faite via le scope `action_required` du model `follow_up`.

Pour les récupérer, on requêtait les suivis dont les invitations avaient été créées il y a + de X jours, jours étant défini via la configuration dans la colonne nouvellement nommée `invitation_duration_in_days`.
=> **Mais cette requête revient ni plus ni moins à requêter les invitations qui ont expirées !** . 

Je change donc la façon de faire en me basant uniquement sur la date d'expiration de l'expiration de l'invitation.
Les `follow_ups` ainsi récupérés sont les `follow_ups` dont le statut est `invitation_pending` (= Invitation en attente de réponse) et dont tous les invitations sont expirées (= délai dépassé)

### Lorsque l'on vérifie la condition pour un suivi

Dans la vue, il y a plusieurs comportements spécifique qui sont activées si le suivi est en statut `invitation_pending` et que les invitations sont expirées:
* On affiche la mention "délai dépassé"
* On affiche une couleur de fond différente (`bg-warning`)
* On affiche le bouton de convocation

Cette condition était vérifiée par la méthode `follow_up#time_to_accept_invitation_exceeded?`. Elle prenait en entrée la durée de validité des invitations (via la `category_configuration`). 
Pareil que pour la requête, on peut éviter de passer ce paramètre en entrée et à la place seulement checker si toutes les invitations sont expirées. 
Ainsi, je change toutes les méthodes du `FollowUpsHelper` pour ne plus prendre en entrée la durée de validité de l'invitation via la `category_configuration`. 

Ce changement est fait ici `FollowUpsHelper` https://github.com/gip-inclusion/rdv-insertion/commit/eb29ab82cf609492a157bbde283db3fc374d530d

Je renomme la méthode `time_to_accept_invitation_exceeded?` en `no_upcoming_rdv_and_invitations_expired?` ici https://github.com/gip-inclusion/rdv-insertion/commit/12da3cd762143d35a20e94abf26bf00c73370fa3

## Suppression du service `Invitations::InvalidateLink`

Je supprime le service `Invitations::InvalidateLink` qui ne faisait pas grand chose au profit d'une méthode `expire!` au sein du model `Invitation`.
J'en profite pour renommer le job `InvalidateInvitationJob` en `ExpireInvitationJob`.

2024-09-11 11:44 UTC, Michaelvilleneuve commented on app/helpers/follow_ups_helper.rb
> +    elsif follow_up.no_upcoming_rdv_and_invitations_expired?
plus clair 👍

2024-09-11 14:54 UTC, Michaelvilleneuve commented on app/models/category_configuration.rb
> +    return if invitation_duration_in_days > Invitation::NUMBER_OF_DAYS_BEFORE_REMINDER
je l'aurais mieux lu dans l'autre sens `minimum_invitation_duration`
D'ailleurs un peu perturbant que la constante s'appelle toujours `NUMBER_OF_DAYS_BEFORE_REMINDER ` on dirait un nom deprecated du coup 😅

2024-09-11 15:03 UTC, Michaelvilleneuve commented on app/services/invite_user.rb
> +      expires_at: @current_configuration.invitation_duration_in_days.days.from_now,
En fait plus je lis plus je trouve pas 100% clair non plus `invitation_duration`, c'est étrange d'avoir une "durée" et c'est pas hyper parlant.
C'est très long mais le plus parlant serait peut-être `number_of_days_before_invitations_expire`

2024-09-11 15:07 UTC, Michaelvilleneuve commented on spec/jobs/expire_invitation_job_spec.rb
> +    context "when the invitation is expired" do
"is already expired" serait plus clair

2024-09-11 20:27 UTC, aminedhobb commented on db/migrate/20240910154029_change_invitations_validity_names.rb
> +    add_index :invitations, :expires_at
Du coup j'ai proposé une solution dans une autre PR (#2320)

2024-09-11 20:28 UTC, aminedhobb commented
Merci @Michaelvilleneuve pour ta review et tes retours pertinents 🙏 , j'ai appliqué la totalité de tes suggestions.

2024-09-12 06:36 UTC, Michaelvilleneuve approved these changes
Top merci pour les changements 🙌

2024-09-12 06:39 UTC, Michaelvilleneuve commented on db/migrate/20240910154029_change_invitations_validity_names.rb
> +    rename_column :category_configurations, :number_of_days_before_action_required, :invitation_duration_in_days
Ah en fait ça ne reflète pas le nouveau nom de la colonne que tu as changé depuis la dernière review : `number_of_days_before_invitations_expire `

2024-09-12 06:39 UTC, Michaelvilleneuve commented on db/migrate/20240910154029_change_invitations_validity_names.rb
> +    add_index :invitations, :expires_at
Oui mais en l'occurence le changement que tu as proposé fera juste échouer la migration, c'est plus safe mais on est pas garanti que ça passe 😬 
Je suis ok pour tenter en l'état mais la table invitations a du volume donc ça me semble dangereux quand même

2024-09-12 06:40 UTC, Michaelvilleneuve requested changes
En fait y'a un petit souci sur la migration encore, et je me pose quand même la question de faire tourner cette migration qui risque causer encore un downtime :/

2024-09-12 08:27 UTC, aminedhobb commented on db/migrate/20240910154029_change_invitations_validity_names.rb
> +    add_index :invitations, :expires_at
Franchement on a jamais eu de soucis jusqu'à présent sur des migrations plus sévère. Mais on est jamais trop prudent tu as raison.
Est-ce que ça te rassurerait de baisser le timeout sur l'autre PR ?
Comme c'est une grosse refacto je comptais pas la déployer en pleine journée de toute façon.

2024-09-12 08:27 UTC, aminedhobb commented on db/migrate/20240910154029_change_invitations_validity_names.rb
> +    rename_column :category_configurations, :number_of_days_before_action_required, :invitation_duration_in_days
Oula bien vu merci 🙏 🙏 !!

2024-09-12 08:36 UTC, Michaelvilleneuve commented on db/migrate/20240910154029_change_invitations_validity_names.rb
> +    add_index :invitations, :expires_at
Disons que le problème c'est que le timeout reste un pansement, ça évite à peu près un downtime (j'espère ?), mais ça peut aussi causer d'autres problèmes, je pense qu'on peut le tenter surtout si on déploie en heures creuses mais faut garder à l'esprit que la bonne pratique c'est le process expliqué au dessus :/

2024-09-12 08:37 UTC, Michaelvilleneuve approved these changes

2024-09-12 08:48 UTC, aminedhobb commented on db/migrate/20240910154029_change_invitations_validity_names.rb
> +    add_index :invitations, :expires_at
> mais ça peut aussi causer d'autres problèmes

À quels problèmes fais-tu référence ?

> la bonne pratique c'est le process expliqué au dessus 

Le process est plus safe oui, mais j'explique dans #2320 pourquoi je fais ce tradeoff: 

"Ça n'empêchera quelques requêtes de ne pas aboutir si on gel une table 5 secondes, mais vu le traffic relativement "faible" sur l'appli et le caractères idempotent de la plupart des actions cela me parait acceptable et moins coûteux que d'avoir un process plus lourd." 

Au moins on s'assure que l'appli ne sera pas down comme hier.

C'est aussi suite à une discussion avec @Holist qui disait que le process expliqué au dessus n'avait pas réglé tous les problèmes rdvsp. 

Après ce n'est que mon avis bien sûr, si vous mettez votre veto on peut faire autrement.

2024-09-16 12:10 UTC, merged