fix(users): filter by convocation
gip-inclusion/rdv-insertion pull request #2408
Opened 2024-10-16 10:28 UTC by Michaelvilleneuve

Cette PR permet de filtrer par date de convocation

Maquette : 
https://www.figma.com/design/NR0YM69JwIzF0KnVYYgcHH/Navigation?node-id=99-2440&node-type=section&t=4P5vxtmsbiNhonE1-0

2024-10-16 11:50 UTC, aminedhobb requested changes
Merci @Michaelvilleneuve , je crois que ce qui était demandé ici c'est de filtrer sur la date de la réception de la notification et pas la date du rdv (c'est précisé dans l'issue).
C'est pour être conforme à ce qu'on affiche sur la page qui est bien la date de la réception de la convocation

2024-10-18 16:26 UTC, aminedhobb commented on app/controllers/invitation_or_convocation_dates_filterings_controller.rb
> +end
Est-ce qu'on pourrait pas avoir trois actions différentes (du style `dates_filters#new`, `convocation_dates_filters#new` et `invitations_dates_filters#new`) ?

La manière dont est organisé le dossier `app/views/invitations_or_convocations_dates_filtering/` me fait penser à un code smell.
À mon avis ce serait plus facile à lire avec des actions séparées mais il y a peut-être une difficulté à faire ça que je n'ai pas en tête.

2024-10-21 08:09 UTC, Michaelvilleneuve commented on app/controllers/invitation_or_convocation_dates_filterings_controller.rb
> +end
En fait comme je disais dans la description de la PR j'ai volontairement pas fait ça car ça faisait beaucoup de routes, 3 controlleurs séparés, et c'était vraiment lourd à gérer pour un workflow qui est autrement très simple. 
Globalement je trouve qu'on est dans un use case qui aurait été très simple et logique avec un framework frontend mais qui là se retrouve inutilement compliqué quand il est géré en backend. 
Ceci étant dit, cette solution m'a finalement semblé la plus simple et permettait justement de ranger ce "double filtre" au sein d'un même dossier

2024-10-29 14:45 UTC, aminedhobb commented on app/controllers/invitation_or_convocation_dates_filterings_controller.rb
> +    render turbo_stream: turbo_stream.replace("remote_modal", partial: "new_#{params[:invitation_type]}")
qu'est-ce que veut dire `invitation_type` ?

2024-10-29 14:54 UTC, aminedhobb commented on app/controllers/invitation_or_convocation_dates_filterings_controller.rb
> +end
> Globalement je trouve qu'on est dans un use case qui aurait été très simple et logique avec un framework frontend

Oui ce serait géré clairement différemment, mais justement le fait d'avoir des actions dédiées est plutôt la façon préconisée de faire avec Hotwire. 
Ça implique de créer des controllers et actions effectivement, subjectivement je ne trouve pas ça très lourd mais ce n'est qu'un ressenti personnel. 
En tous cas j'ai l'impression qu'on gagne beaucoup en clarté à avoir des actions dédiée plutôt que de passer un paramètre. WDYT ?

2024-10-30 09:06 UTC, Michaelvilleneuve commented on app/controllers/invitation_or_convocation_dates_filterings_controller.rb
> +    render turbo_stream: turbo_stream.replace("remote_modal", partial: "new_#{params[:invitation_type]}")
J'avais pas de bon nommage mais concrétement c'est soit invitation soit convocation

2024-10-30 16:46 UTC, aminedhobb reviewed
Merci pour les changements @Michaelvilleneuve , à titre personnel je trouve ça plus cohérent cette façon de faire et plus flexible en cas de changements.
Après j'ai l'impression que tu n'es pas convaincu :), et je n'ai pas envie d'imposer des choix techs de manière unilatérales, donc si tu n'es pas à l'aise avec cette réécriture on peut aussi en discuter avec @Holist et essayer de trouver un consensus (et aller possiblement au-delà de cette petite feature mais sur la manière de gérer le front-end sur l'appli)

2024-10-30 16:47 UTC, aminedhobb submitted a review, later dismissed

2024-10-30 16:58 UTC, aminedhobb commented on app/controllers/dates_filterings/convocation_dates_filterings_controller.rb
> +      render turbo_stream: turbo_stream.replace("remote_modal", partial: "new")
Je crois que si tu rajoutes l'attribut `data-turbo-frame="remote_modal"` au lien de la modale précédente, tu n'as pas besoin de répondre en turbo stream ici. 
À voir comment faire via le JS.
Pareil pour l'invitation

2024-10-31 15:32 UTC, aminedhobb approved these changes
Merci pour les changements 🙏 🚀

2024-10-31 15:32 UTC, aminedhobb commented on app/views/dates_filterings/choose_date_kind/new.html.erb
> +  <%= form_with method: :get, local: true, data: { "turbo-frame" => "_top" }, data: { controller: "dates-filtering" } do |form| %>
`data: { "turbo-frame" => "_top" },` n'est pas utile ici parce qu'on reste dans la frame 

```suggestion
<%= render "common/remote_modal", title: "Filtrer par date d'invitation ou de convocation" do %>
  <%= form_with method: :get, local: true, data: { controller: "dates-filtering" } do |form| %>
```

2024-11-07 10:24 UTC, merged