feat(parcours): improve overlap management
gip-inclusion/rdv-insertion pull request #2424
Opened 2024-10-24 15:54 UTC by Michaelvilleneuve

2024-10-29 09:12 UTC, Michaelvilleneuve commented on app/views/users/orientations/_confirm_override_overlap.html.erb
> +      <% end %>
Ici j'ai fait un `form` plutôt qu'un simple lien car sinon il ne dismiss pas complètement la modale et on se retrouve avec un empilement de modale qu'on ne peut plus dismiss

2024-10-29 09:13 UTC, Michaelvilleneuve commented on app/services/orientations/save.rb
> +      @orientation.ends_at = posterior_orientations.min_by(&:starts_at).starts_at - 1.day
Ici le ticket précise bien `on raccourcit l’orientation précédent la veille du jour de début de la nouvelle orientation`

2024-10-30 17:52 UTC, aminedhobb requested changes
Merci @Michaelvilleneuve 👍 ! 
J'ai quelques doutes sur certains chevauchements qu'on ne détecterait plus avec cette nouvelle implémentation, LMKWYT :)

2024-10-31 10:27 UTC, Michaelvilleneuve commented on app/services/orientations/save.rb
> +        overlapping_orientations.first.update!(ends_at: @orientation.starts_at - 1.day)
En fait on prend le first car théoriquement c'est le résultat d'un where, mais dans les faits il ne peut y en avoir qu'un seul à ce moment (sauf écriture concurrente) car ce code n'est appelé que si overlapping_orientations.size est == 1
```ruby
return if overlapping_orientations.empty?

      if overlapping_orientations.size > 1
        return fail!(
          "Cette orientation chevauche plusieurs autres orientations, veuillez adapter les dates de début et de fin"
        )
      end

      if overrideable_overlap?
        result.errors << { overrideable_overlap: true, overlapping_orientation: overlapping_orientations.first }
        return fail!
      end

      fail!("Cette orientation chevauche une autre orientation qui ne peut être raccourcie automatiquement,
                    veuillez modifier l'orientation en question ou changer les dates renseignées ci-dessous")
```

2024-11-07 13:57 UTC, Michaelvilleneuve commented on app/services/orientations/save.rb
>      end
Non tu peux pas le faire à la ligne 60 car la ligne 60 est appelée une fois que tu as déjà la modale affichée et que tu confirmes le raccourcissement

Ligne 88 c'est appelé au passage d'avant, pour savoir si oui on non on doit afficher la modale

2024-11-07 17:37 UTC, Michaelvilleneuve commented on app/views/common/_remote_modal.html.erb
> +    <% else %>
ah oui effectivement je viens de retester sans et ça marche quand même, je sais pas trop pourquoi j'avais mis ça à un moment du coup :thinking_face:

2024-11-13 15:00 UTC, aminedhobb commented on spec/services/orientations/save_spec.rb
> +            described_class.call(orientation:, update_anterior_ends_at: true)
Je comprends pas pourquoi on a besoin de mettre l'option `update_anterior_ends_at` ici

2024-11-13 15:01 UTC, aminedhobb commented on spec/services/orientations/save_spec.rb
> +            expect(second_orientation.reload.ends_at).to eq(starts_at - 1.day)
ah c'est pour ça. Je pense qu'on peut enlever cette expectation et juste dire `stays nil`, parce que le previous ends_at on l'a testé plus haut

2024-11-13 15:02 UTC, aminedhobb commented on spec/services/orientations/save_spec.rb
>            it "sets the ends_at at the posterior starts_at" do
```suggestion
          it "sets the ends_at one day before the posterior starts_at" do
```

2024-11-13 15:07 UTC, aminedhobb commented on spec/services/orientations/save_spec.rb
> +          expect(subject.errors.first).to include("Cette orientation chevauche")
pour être homogène ;)
```suggestion
          expect(subject.errors.first).to include("Cette orientation chevauche une autre orientation")
```

2024-11-13 15:08 UTC, aminedhobb commented on spec/services/orientations/save_spec.rb
> +          expect(subject.errors.first).to include("Cette orientation chevauche")
```suggestion
          expect(subject.errors.first).to include("Cette orientation chevauche une autre orientation")
```

2024-11-13 15:10 UTC, aminedhobb commented on spec/services/orientations/save_spec.rb
> +            create(:orientation, user:, starts_at: Date.parse("21/11/2022"), ends_at: nil)
gros nitpick: J'ai pas très bien compris pourquoi on devait changer cette variable au début. On aurait éventuellement pu tester le cas où on la change pas et que l'orientation ne peut donc pas être sauvée (pas obligé ceci dit vu que la validation se fait au niveau du modèle)

2024-11-14 10:12 UTC, Michaelvilleneuve commented on spec/services/orientations/save_spec.rb
> +            expect(second_orientation.reload.ends_at).to eq(starts_at - 1.day)
Oui mais je suis quand même obligé de laisser `update_anterior_ends_at ` car sinon il me lève l'erreur avec la shrinkeable_orientation

2024-11-14 10:13 UTC, Michaelvilleneuve commented on spec/services/orientations/save_spec.rb
> +            described_class.call(orientation:, update_anterior_ends_at: true)
Car sinon le service bloque car il détecte que l'orientation précédente est shrinkeable

2024-11-14 11:09 UTC, Michaelvilleneuve commented on app/models/orientation.rb
> +      .where("starts_at <= ?", orientation.starts_at - Orientation::MINIMUM_DURATION_IN_DAYS.days)
J'ai simplifié la condition, on prends désormais juste celle qui comment au moins 8 jours avant la date de début de la nouvelle et qui terminent après ou jamais.
Plus simple à lire, je pense pas que ça nécessite commentaire, wdyt ?

2024-11-14 17:11 UTC, aminedhobb commented on app/models/orientation.rb
> +      .where("starts_at <= ?", orientation.starts_at - Orientation::MINIMUM_DURATION_IN_DAYS.days)
Le `orientation.starts_at.yesterday` c'est un peu dur à lire quand même 😅  . 
Je serais plus pour mettre le `- 1.day` explicitement, et rajouter un commentaire pour dire que la précédente orientation doit commencer 8 jours avant la date de la nouvelle pour être rétrécissable. Ce sera + simple à la relecture quand quelqu'un tombera sur ce code.

2024-11-20 15:32 UTC, aminedhobb approved these changes
👍 🚢

2024-11-20 15:32 UTC, merged