feat(view): Display rdv seen date on users index
gip-inclusion/rdv-insertion pull request #2490
Opened 2024-11-20 17:22 UTC by aminedhobb

Closes #2454 

Je rajoute la date du rdv honoré lorsque le statut du suivi est "RDV honoré".
J'en profite pour ajouter des commentaires sur des parties qui n'étaient pas forcément explicites.

2024-11-20 21:07 UTC, Michaelvilleneuve commented on app/views/follow_ups/_follow_up_status_cell.html.erb
> +  <!-- We need to check the participations presence on top of the statuses since the follow_up status is updated asynchronously, so for a brief period of time the follow_up can be in status rdv_pendi
Ce commentaire devrait être fait en Ruby pas en html car là il se retrouve dans le DOM alors qu'il concerne une subtilité d'implémentation backend

2024-11-20 21:07 UTC, Michaelvilleneuve requested changes
Juste un petit changement mineur sinon all good 👍

2024-11-21 10:19 UTC, aminedhobb commented on app/views/follow_ups/_follow_up_status_cell.html.erb
> +  <!-- We need to check the participations presence on top of the statuses since the follow_up status is updated asynchronously, so for a brief period of time the follow_up can be in status rdv_pendi
Oups bien vu merci ! J'ai changé ici: https://github.com/gip-inclusion/rdv-insertion/pull/2490/commits/b1e2064c0ac5049ecaad44492f998540350a1c54

2024-11-21 10:46 UTC, Michaelvilleneuve submitted a review, later dismissed
Merci pour le changement 👍

2024-11-21 14:27 UTC, merged